version: '2'
services:
  weblate:
    container_name: weblatedocker_weblate_1
    build: weblate
    links:
      - database
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./weblate/environment
    restart: always
  web:
    container_name: weblatedocker_web_1
    build: nginx
    links:
      - weblate
    ports:
      - 80
    volumes_from:
      - weblate:ro
    restart: always
  database:
    container_name: weblatedocker_database_1
    image: postgres:9.4
    env_file:
      - ./weblate/environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    container_name: weblatedocker_cache_1
    image: memcached:1.4
    restart: always
volumes:
  weblate-data: {}
  postgres-data: {}
